[package]
name = "tcp_to_can"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
    tokio = { version = "1.38.0", features = ["full"] }
    slint = "1.6.0"
